permalink: /:year/:month/:title/

markdown:         rdiscount
pygments:         true
paginate:         1
paginate_path:    /page/:num
destination:      _site/blog

title:            Baconrad
url:              http://Baconrad.com
feed:             /atom.xml
author:
    name:         Baconrad
description:      "Baconrad\'s Blog"